email: ""
password: ""

disableAntiLock: false
remote: false

experienceLevel:
  internship: false
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: true
  month: false
  week: false
  24 hours: false

positions:
  - "Software Engineer"
  - "Backend Developer"

locations:
  - "Berlin, Germany"
  - "Munich, Germany"
  - "New York, USA"
  - "San Francisco, USA"


distance: 25

outputFileDirectory: "/home/pythondevai/projects/LinkedIn-Easy-Apply-Bot/output"

companyBlacklist: []
titleBlacklist: []

uploads:
  resume: "/home/pythondevai/projects/LinkedIn-Easy-Apply-Bot/Resume Timileyin Updated Full.pdf"
  coverLetter: "/home/pythondevai/projects/LinkedIn-Easy-Apply-Bot/Resume Timileyin Updated Full.pdf"

checkboxes:
  driversLicence: true
  requireVisa: false
  legallyAuthorized: true
  urgentFill: true
  commute: true
  degreeCompleted:
    - "High School Diploma"
    - "Bachelor's Degree"
  backgroundCheck: true

universityGpa: 4.17

languages:
  english: "Native or bilingual"

industry:
  Accounting/Auditing: 0
  Administrative: 0
  Advertising: 0
  Analyst: 0
  Art/Creative: 0
  Business Development: 0
  Consulting: 0
  Customer Service: 0
  Distribution Design: 0
  Education: 0
  Engineering: 0
  Finance: 0
  General Business: 0
  Health Care Provider: 0
  Human Resources: 0
  Information Technology: 0
  Legal: 0
  Management: 0
  Manufacturing: 0
  Marketing: 0
  Public Relations: 0
  Purchasing: 0
  Product Management: 0
  Project Management: 0
  Production: 0
  Quality Assurance: 0
  Research: 0
  Sales: 0
  Science: 0
  Strategy/Planning: 0
  Supply Chain: 0
  Training: 0
  Writing/Editing: 0
  default: 0

technology:
  python: 3
  typescript: 3
  default: 2


personalInfo:
  First Name: ""
  Last Name: ""
  Phone Country Code: "Nigeria (+234)"
  Mobile Phone Number: ""
  Street address: ""
  Country: ""
  City: ""
  State: ""
  Zip: ""
  Linkedin: ""
  Website: ""

eeo:
  gender: male
  race: None
  vetran: None
  disability: None
  citizenship: Nigerian
